version: '3'
services:
  bot2:
    build: .
    networks:
      - nginx_app-network
    container_name: bot2
    restart: unless-stopped
    #    env_file: env.

networks:
  nginx_app-network:
    external: true
